name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-fossa

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      run: |
           wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-x86_64-aarch64-none-elf.tar.xz
           tar xf gcc-arm-*-*.tar.xz 
           export PATH=$(readlink -f ./gcc-*/bin/):$PATH
    - name: Build circle-stdlib library
      run: |
           cd circle-stdlib/
           git submodule update --init
           ./configure -r 4 --prefix "aarch64-none-elf-"
           ( cd libs/circle ; git submodule update --init ) # FIXME: Find a way without the need for this
           make -j$(nproc)
           cd ..
    - name: Build MiniDexed
      run: |
           make -j$(nproc)
           ls *.img
